import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 12.0

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
