#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## Monitor names ---------------------------------------------#

## Get monitor names
INTERNAL_MONITOR=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | head -n 1)
EXTERNAL_MONITOR=$(xrandr -q | grep " connected" | cut -d ' ' -f1 | tail -n 1)

## General ---------------------------------------------------

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#DE898E'
BSPWM_NBC='#1E1E2E'
BSPWM_ABC='#F5C2E7'
BSPWM_PFC='#A6E3A1'

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='15'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '' '' '' '' '' '' '' ''
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		xrandr --output "$INTERNAL_MONITOR" --primary --mode 2560x1440 --rate 170 --pos 1920x0 --rotate normal \
			--output "$EXTERNAL_MONITOR" --mode 1920x1080 --rate 144 --pos 0x0 --rotate normal
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' '' '' 'ﳴ'
		bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' '' '' '' '' '' '' 'ﳴ'
	else
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' '' '' 'ﳴ'
	fi
}

## Three Monitors Setup (Laptop and two external monitor, 3-2-3 workspaces)
three_monitors_workspaces() {
	# again, change these values accordingly
	MONITOR_1="eDP"
	MONITOR_2="HDMI-A-0"
	MONITOR_3="HDMI-A-1"
	bspc monitor "$MONITOR_1" -d '' ''
	bspc monitor "$MONITOR_2" -d '' '' ''
	bspc monitor "$MONITOR_3" -d '' '' ''
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

## Uncomment only one function according to your needs
# default_workspaces
two_monitors_workspaces
#three_monitors_workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
# bspc rule -a Alacritty desktop='^1' follow=on focus=on
# bspc rule -a Xfce4-terminal desktop='^1' follow=on focus=on

## 2 > web (always open web browser on workspace-2)
bspc rule -a firefox desktop='focused:^2' follow=on focus=on
bspc rule -a chromium desktop='focused:^2' follow=on focus=on

## 3 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(Gucharmap Atril Evince \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='focused:^3' follow=on focus=on; done

# no border for workspace 3
bspc config -m "$INTERNAL_MONITOR" -d 'focused:^3' window_gap 0
bspc config -m "$INTERNAL_MONITOR" -d 'focused:^3' border_width 0

## 4 > code (always open editors on workspace-4)
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='focused:^4' follow=on focus=on; done

## 5 > files (always open file manager on workspace-3)
declare -a files=(Pcmanfm Thunar qBittorrent)
for i in ${files[@]}; do
   bspc rule -a $i desktop='focused:^5' follow=on focus=on; done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(Thunderbird TelegramDesktop Hexchat discord)
for i in ${comm[@]}; do
   bspc rule -a $i monitor='$EXTERNAL_MONITOR' desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Audacity Music MPlayer Lxmusic Inkscape Gimp-2.10 Spotify obs)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done
# smaller window for spotify
bspc rule -a Spotify state=floating rectangle=1600x900+0+0

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='focused:^8' follow=on focus=on
bspc rule -a GParted desktop='focused:^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='focused:^8' state=floating follow=on focus=on; done

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash ~/.fehbg

# Keyboard layout
setxkbmap -layout us,cz -option grp:switch,grp:alt_shift_toggle,caps:escape

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &

# Start apps
redshift &
spotify &
discord &
